### ISSUE TITLE
Suggestion: Amiga emulator vAmiga

### ISSUE THREAD

**Issue by nekoniaow** [mcicolella/awesome-emulators-simulators#15]
I noticed the vAmiga emulator was not listed, you may want to include it.

It works exclusively on Mac: https://dirkwhoffmann.github.io/vAmiga/.

**Comment by mcicolella** [comment]
@nekoniaow thanks a lot. I'll add it ASAP.

**Comment by mcicolella** [comment]
Just added in df2188960aa4479df7d6f43b3709281477d10de1
Thanks
